name: Build openvino plugins

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  AUDACITY_REPO: audacity/audacity
  AUDACITY_BRANCH: main
  AUDACITY_VERSION: audacity-main

  SOURCE_PATH: ${{ github.workspace }}/code

jobs:
  build-openvino-plugins:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}

      - name: Checkout audacity
        uses: actions/checkout@v4
        with:
          repository: ${{ env.AUDACITY_REPO }}
          ref: ${{ env.AUDACITY_BRANCH }}
          path: ${{ env.SOURCE_PATH }}/${{ env.AUDACITY_VERSION }}

      - name: Build audacity
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" ${{ env.SOURCE_PATH }}/${{ env.AUDACITY_VERSION }} -DCMAKE_BUILD_TYPE=Release
          make -j`sysctl -n hw.ncpu`
